import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Alert, Box, Button, Card, CardActionArea, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, IconButton, MenuItem, Snackbar, Stack, TextField, Tooltip, Typography } from "@mui/material";
import { DataGrid, type GridColDef, type GridPaginationModel } from "@mui/x-data-grid";
import AddCircleOutlineIcon from "@mui/icons-material/AddCircleOutline";
import AttachFileOutlinedIcon from "@mui/icons-material/AttachFileOutlined";
import BlockOutlinedIcon from "@mui/icons-material/BlockOutlined";
import DashboardOutlinedIcon from "@mui/icons-material/DashboardOutlined";
import PaymentsOutlinedIcon from "@mui/icons-material/PaymentsOutlined";
import ReceiptLongOutlinedIcon from "@mui/icons-material/ReceiptLongOutlined";
import ShoppingCartOutlinedIcon from "@mui/icons-material/ShoppingCartOutlined";
import TaskAltIcon from "@mui/icons-material/TaskAlt";
import UndoOutlinedIcon from "@mui/icons-material/UndoOutlined";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useSearchParams } from "react-router-dom";
import useAuthorizedClient from "../../hooks/useAuthorizedClient";
import { useAuth } from "../../context/AuthContext";
import { formatCurrency } from "../../utils/currency";
import UnusedBudgetDialog from "../common/UnusedBudgetDialog";

type PendingFilter = "all" | "request" | "expense" | "invoice";
type PendingStep = "request_pending" | "expense_pending" | "invoice_pending";
type PendingItem = { plan_id:number; budget_item_id:number; scenario_id:number; year:number; month:number; department?:string|null; budget_code?:string|null; budget_item:string; capex_opex?:string|null; nitelik?:string|null; planned_amount:number; expense_total:number; remaining_amount:number; unused_amount:number; pending_step:PendingStep; pending_step_label:string; purchase_request_pending:boolean; purchase_request_created:boolean; expense_missing:boolean; invoice_missing:boolean; missing_invoice_expense_id?:number|null; description?:string|null };
type PendingResponse = { items:PendingItem[]; total:number; counts:{all:number;request_pending:number;expense_pending:number;invoice_pending:number} };
const months=["","Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"];
const errorMessage=(error:unknown)=>String((error as any)?.response?.data?.detail??"İşlem tamamlanamadı.");

export default function PendingExpensesView(){
  const client=useAuthorizedClient(); const queryClient=useQueryClient(); const navigate=useNavigate(); const {user}=useAuth(); const [params,setParams]=useSearchParams();
  const normalizeFilter=(value:string):PendingFilter=>["purchase","purchase-pending","request-pending"].includes(value)?"request":["all","request","expense","invoice"].includes(value)?value as PendingFilter:"all";
  const [filter,setFilterState]=useState<PendingFilter>(normalizeFilter(params.get("filter")||"all"));
  const [year,setYear]=useState(params.get("year")||""); const [month,setMonth]=useState(params.get("month")||""); const [department,setDepartment]=useState(""); const [reason,setReason]=useState(""); const [search,setSearch]=useState("");
  const [pagination,setPagination]=useState<GridPaginationModel>({page:0,pageSize:50});
  const [feedback,setFeedback]=useState<{severity:"success"|"error";message:string}|null>(null); const fileInput=useRef<HTMLInputElement|null>(null); const [invoiceExpenseId,setInvoiceExpenseId]=useState<number|null>(null);
  const [revertRow,setRevertRow]=useState<PendingItem|null>(null); const [unusedRow,setUnusedRow]=useState<PendingItem|null>(null);
  const [,setUnusedAmount]=useState(""); const [,setUnusedError]=useState<string|null>(null);
  const isViewer=["viewer","readonly","read_only"].includes(String(user?.role??"").toLowerCase());
  useEffect(()=>{setFilterState(normalizeFilter(params.get("filter")||"all"));setPagination(current=>({...current,page:0}))},[params]);
  const query=useQuery<PendingResponse>({queryKey:["pending-budget-actions",year,month,department,reason,filter,search,pagination],queryFn:async()=>(await client.get<PendingResponse>("/expenses/pending-budget-actions",{params:{year:year||undefined,month:month||undefined,department_id:department||undefined,pending_reason:reason||undefined,pending_type:filter,search:search||undefined,page:pagination.page+1,page_size:pagination.pageSize}})).data});
  const items=query.data?.items??[]; const counts=query.data?.counts??{all:0,request_pending:0,expense_pending:0,invoice_pending:0};
  const years=useMemo(()=>Array.from(new Set(items.map(i=>i.year))).sort((a,b)=>b-a),[items]); const departments=useMemo(()=>Array.from(new Set(items.map(i=>i.department).filter(Boolean) as string[])).sort(),[items]);
  const refresh=()=>["pending-budget-actions","expenses-pending","purchase-pending","expenses","plans","dashboard"].forEach(key=>queryClient.invalidateQueries({queryKey:[key]}));
  const purchaseMutation=useMutation({mutationFn:(row:PendingItem)=>client.patch(`/plan-items/${row.plan_id}/purchase-requested`,{requested:true}),onSuccess:()=>{refresh();setFeedback({severity:"success",message:"Satın alma talebi oluşturuldu olarak kaydedildi."})},onError:e=>setFeedback({severity:"error",message:errorMessage(e)})});
  const revertPurchaseMutation=useMutation({mutationFn:(row:PendingItem)=>client.patch(`/plan-items/${row.plan_id}/purchase-requested`,{requested:false}),onSuccess:()=>{setRevertRow(null);refresh();setFeedback({severity:"success",message:"Talep oluşturuldu işareti geri alındı."})},onError:e=>setFeedback({severity:"error",message:errorMessage(e)})});
  const invoiceMutation=useMutation({mutationFn:async({expenseId,file}:{expenseId:number;file:File})=>{const data=new FormData();data.append("files",file);await client.post(`/expenses/${expenseId}/attachments/batch`,data)},onSuccess:()=>{refresh();setFeedback({severity:"success",message:"Fatura eklendi."})},onError:e=>setFeedback({severity:"error",message:errorMessage(e)})});
  const setFilter=(next:PendingFilter)=>{setFilterState(next);setPagination(current=>({...current,page:0}));const updated=new URLSearchParams(params);updated.set("filter",next);setParams(updated,{replace:true})};
  const columns=useMemo<GridColDef<PendingItem>[]>(()=>[
    {field:"year",headerName:"Yıl",width:72},{field:"month",headerName:"Ay",width:92,valueGetter:v=>months[Number(v)]||v},{field:"department",headerName:"Departman",minWidth:125,flex:.55},{field:"budget_item",headerName:"Bütçe Kalemi",minWidth:200,flex:1.1},{field:"capex_opex",headerName:"Capex/Opex",width:105},{field:"nitelik",headerName:"Nitelik",minWidth:110,flex:.5},
    ...(["planned_amount","expense_total","remaining_amount"] as const).map((field,index)=>({field,headerName:["Planlanan","Toplam Harcama","Kalan"][index],width:135,align:"right" as const,headerAlign:"right" as const,valueFormatter:(v:unknown)=>formatCurrency(Number(v))})),
    {field:"pending_step",headerName:"Bekleyen Adım",minWidth:170,flex:.65,renderCell:({row})=><Chip size="small" variant={row.pending_step==="request_pending"?"outlined":"filled"} color={row.pending_step==="request_pending"?"info":row.pending_step==="expense_pending"?"warning":"error"} label={row.pending_step_label}/>},
    {field:"actions",headerName:"İşlemler",minWidth:180,sortable:false,renderCell:({row})=><Stack direction="row" spacing={.5}>{row.pending_step==="request_pending"&&<Tooltip title="Satın alma talebini oluşturuldu olarak işaretle"><IconButton size="small" color="primary" disabled={isViewer||purchaseMutation.isPending} onClick={()=>purchaseMutation.mutate(row)}><TaskAltIcon fontSize="small"/></IconButton></Tooltip>}{row.purchase_request_created&&<Tooltip title="Talep oluşturuldu işaretini geri al"><IconButton size="small" color="warning" disabled={isViewer||revertPurchaseMutation.isPending} onClick={()=>setRevertRow(row)}><UndoOutlinedIcon fontSize="small"/></IconButton></Tooltip>}{row.pending_step==="expense_pending"&&<Tooltip title="Bu bütçe kalemine harcama ekle"><IconButton size="small" color="primary" disabled={isViewer} onClick={()=>navigate("/expenses",{state:{openCreate:true,year:row.year,month:row.month,scenarioId:row.scenario_id,budgetItemId:row.budget_item_id}})}><AddCircleOutlineIcon fontSize="small"/></IconButton></Tooltip>}{row.pending_step==="invoice_pending"&&row.missing_invoice_expense_id&&<Tooltip title="Eksik faturayı ekle"><IconButton size="small" color="secondary" disabled={isViewer} onClick={()=>{setInvoiceExpenseId(row.missing_invoice_expense_id!);fileInput.current?.click()}}><AttachFileOutlinedIcon fontSize="small"/></IconButton></Tooltip>}<Tooltip title="Bütçe kalemini kullanılmayacak olarak işaretle"><IconButton size="small" color="warning" disabled={!user?.is_admin||row.remaining_amount<=0} onClick={()=>{setUnusedRow(row);setUnusedAmount("");setUnusedError(null)}}><BlockOutlinedIcon fontSize="small"/></IconButton></Tooltip></Stack>}
  ],[isViewer,navigate,purchaseMutation,revertPurchaseMutation,user?.is_admin]);
  const cards:[PendingFilter,ReactNode,number,string][]=[["all",<><DashboardOutlinedIcon fontSize="small"/> Tümü</>,counts.all,"primary.main"],["request",<><ShoppingCartOutlinedIcon fontSize="small"/> Talep Bekleyen</>,counts.request_pending,"info.main"],["expense",<><PaymentsOutlinedIcon fontSize="small"/> Harcama Bekleyen</>,counts.expense_pending,"warning.main"],["invoice",<><ReceiptLongOutlinedIcon fontSize="small"/> Fatura Bekleyen</>,counts.invoice_pending,"error.main"]];
  return <Stack spacing={2}>
    <Box><Typography variant="h4" fontWeight={800}>Bekleyen Bütçe İşlemleri</Typography><Typography color="text.secondary">Satın alma talebi, harcama veya fatura işlemi bekleyen bütçe kalemleri</Typography></Box>
    <Stack direction={{xs:"column",md:"row"}} spacing={1.25}>{cards.map(([id,label,count,color])=><Card key={id} variant="outlined" sx={{flex:1,borderWidth:filter===id?2:1,borderColor:filter===id?color:"divider",bgcolor:filter===id?"action.selected":"background.paper",transition:".15s","&:hover":{transform:"translateY(-2px)",boxShadow:2}}}><CardActionArea onClick={()=>setFilter(id)}><CardContent sx={{py:1.5}}><Typography component="div" variant="body2" color={color} sx={{display:"flex",alignItems:"center",gap:.75}}>{label}</Typography><Typography variant="h5" fontWeight={800}>{count}</Typography></CardContent></CardActionArea></Card>)}</Stack>
    <Stack direction={{xs:"column",md:"row"}} spacing={1}><TextField size="small" label="Yıl" value={year} onChange={e=>setYear(e.target.value)} sx={{width:110}}/><TextField select size="small" label="Ay" value={month} onChange={e=>setMonth(e.target.value)} sx={{minWidth:130}}><MenuItem value="">Tümü</MenuItem>{months.slice(1).map((v,i)=><MenuItem key={v} value={i+1}>{v}</MenuItem>)}</TextField><TextField select size="small" label="Departman" value={department} onChange={e=>setDepartment(e.target.value)} sx={{minWidth:170}}><MenuItem value="">Tümü</MenuItem>{departments.map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField size="small" label="Ara" value={search} onChange={e=>setSearch(e.target.value)} sx={{flex:1}}/></Stack>
    <Box sx={{overflowX:"auto"}}><DataGrid autoHeight rows={items} rowCount={query.data?.total??0} paginationMode="server" paginationModel={pagination} onPaginationModelChange={setPagination} getRowId={r=>r.plan_id} columns={columns} loading={query.isFetching} disableRowSelectionOnClick pageSizeOptions={[20,50,100]} sx={{minWidth:1400}}/></Box>
    <input ref={fileInput} hidden type="file" accept="application/pdf" onChange={e=>{const file=e.target.files?.[0];if(file&&invoiceExpenseId)invoiceMutation.mutate({expenseId:invoiceExpenseId,file});e.target.value=""}}/>
    <UnusedBudgetDialog planId={unusedRow?.plan_id??null} onClose={()=>setUnusedRow(null)} onSuccess={message=>setFeedback({severity:"success",message})}/>
    <Dialog open={Boolean(revertRow)} onClose={()=>!revertPurchaseMutation.isPending&&setRevertRow(null)}><DialogTitle>Talep durumu geri alınsın mı?</DialogTitle><DialogContent><DialogContentText>Bu bütçe kalemi tekrar Talep Bekleyen durumuna alınacaktır. Harcama ve fatura kayıtları etkilenmeyecektir.</DialogContentText></DialogContent><DialogActions><Button onClick={()=>setRevertRow(null)}>Vazgeç</Button><Button variant="contained" color="warning" onClick={()=>revertRow&&revertPurchaseMutation.mutate(revertRow)}>Talebi Geri Al</Button></DialogActions></Dialog>
    <Snackbar open={Boolean(feedback)} autoHideDuration={4500} onClose={()=>setFeedback(null)}>{feedback?<Alert severity={feedback.severity}>{feedback.message}</Alert>:undefined}</Snackbar>
  </Stack>;
}
